# Generated by Django 5.1.6 on 2025-02-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLEData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100)),
                ('rssi', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('service_uuid', models.CharField(max_length=100)),
                ('manufacturer_data', models.CharField(max_length=100)),
            ],
        ),
    ]
