# Generated by Django 5.1.6 on 2025-04-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bledata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bledata',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
