# Generated by Django 5.1.6 on 2025-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bledata', '0002_bledata_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bledata',
            name='environment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
